build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - >-
        echo "{
        \"auths\": {
        \"$CI_REGISTRY\": {
        \"username\":\"$CI_REGISTRY_USER\",
        \"password\":\"$CI_REGISTRY_PASSWORD\"
        }}}" > /kaniko/.docker/config.json
    - >-
        /kaniko/executor --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
        --destination $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
  only:
    - multiprocess
  except:
    variables:
      - $BUILD_DISABLED

